### ISSUE TITLE
为什么不显示呢？

### ISSUE THREAD

**Issue by Sky0372Lsk** [DamonHu/HDWindowLogger#1]
我新建了一个项目，和你github上的一摸一样，但是不显示log信息，只显示左下角那个按钮，奇怪

**Comment by DamonHu** [comment]
使用`HDNormalLog(@"点击按钮"); `等输出之后才会输出信息，不是用`NSLog`输出的

**Comment by Sky0372Lsk** [comment]
我知道HDNormalLog这样输出。初步看了一下，是最新的Xcode项目问题，带SceneDelegate的都不显示，老的项目结构还能显示。我在微信公众号也联系你了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Damon"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 下午2:02
收件人: "DamonHu/HDWindowLogger"<HDWindowLogger@noreply.github.com&gt;; 
抄送: "李尚锴"<2539829389@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DamonHu/HDWindowLogger] 为什么不显示呢？ (#1)




使用HDNormalLog(@"点击按钮"); 等输出之后才会输出信息，不是用NSLog输出的

**Comment by DamonHu** [comment]
那应该是获取window的方式在使用`SceneDelegate`时有问题，我看看修复一下

**Comment by DamonHu** [comment]
1.6.11版本已修复，兼容scene
