### ISSUE TITLE
悬浮H按钮，移动有点问题，出现闪烁，位置不对的情况

### ISSUE THREAD

**Issue by lijiang0818** [DamonHu/HDWindowLogger#2]

**Comment by DamonHu** [comment]
因为现在主要是Swift开发，强烈推荐你使用这个库的Swift版本：[ZXKitCode/ZXKitLogger](https://github.com/ZXKitCode/ZXKitLogger)，有更多的功能和更新。你反馈的这个bug今天晚点时候我看看修复下

**Comment by DamonHu** [comment]
已修复，pod拉取最新版本即可
